name: "[CI] Lint"

on:
  push:
  pull_request:

env:
  RUBY_VERSION: 3.0.2
  NODE_VERSION: 16.9.1

jobs:
  lint-report:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - run: npm ci
        name: Install JS deps

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - run: bundle exec erblint app/{cells,views}/**/*.erb
        name: Lint ERB files

      - run: npm run lint
        name: Lint JS files
